</FONT></TD>
         </TR>
        </TABLE><TABLE cellpadding=0 cellspacing=0 border=0 width="99%"
                align=center    bgcolor="ffffff">
            <TR>
             <TD colspan=3 align=center><IMG src="/images/greendot.gif"
                alt="" width="80%" height=1 hspace=10 vspace=30></TD>
            </TR><TR>
             <TD align=center><FONT size=2 face="arial,helvetica">
  <FORM method=GET action="http://matthewg.port.net/search.pl">
         <INPUT type=name name=query value="" width=20 size=20 length=20>
        <INPUT type=submit value="Search">
  </FORM>
  </FONT>
  </TD>
  <TD bgcolor="#ffffff" width=25>  &nbsp; </TD>
  <TD align=center>
    <FONT size=2 face="arial,helvetica"><I>This site is based on the Slash Engine</I></FONT><BR>
    <A href=http://slashdot.org><IMG src=/images/slashdotlogo.gif width=100 height=34 border=0></A>
    </FONT>
  </TD></TR>
  <TR><TD colspan=3 align=center>
  <FONT size=1 color="#00666" face="arial,helvetica">

 All trademarks and copyrights on this
  page are owned by their respective companies.  Comments
  are owned by the Poster.
  The Rest © 1999 The Management
</FONT></CENTER>
             </TD>
            </TR>
           </TABLE>
        <CENTER>
          <FONT size=2 color="#006666">
	[ <FONT size=2><B>         
&nbsp;<A href=http://matthewg.port.net/~mp3/>MP3s</A> |
&nbsp;<A href=http://www.zevils.com/linux/mp3tools/>mp3tools</A> |
&nbsp;<A href=http://matthewg.port.net/search.pl>older stuff</A> |
&nbsp;<A href=http://matthewg.port.net/submit.pl>submit story</A> |
&nbsp;<A href=http://matthewg.port.net/users.pl>user account</A> |
&nbsp;<A href=http://matthewg.port.net/pollBooth.pl>past polls</A> |
&nbsp;<A href=http://matthewg.port.net/topics.shtml>topics</A> |
&nbsp;<A href=http://matthewg.port.net/faq.shtml>faq</A> |
&nbsp;<A href=http://matthewg.port.net/hof.shtml>hof</A>
</B></FONT>
 ]
           </FONT>
          </CENTER>

</BODY>
</HTML>