# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "groups", :force => true do |t|
    t.column "login",    :string,                     :null => false
    t.column "password", :string
    t.column "address",  :string,                     :null => false
    t.column "admin",    :boolean, :default => false, :null => false
  end

  create_table "meals", :force => true do |t|
    t.column "name", :string, :null => false
  end

  create_table "people", :force => true do |t|
    t.column "name",      :string,                     :null => false
    t.column "attending", :boolean, :default => false, :null => false
    t.column "meal_id",   :integer
    t.column "group_id",  :integer,                    :null => false
  end

end
