#!/usr/bin/perl

sub BEGIN {
	my $home = (getpwuid($>))[7];
	push @INC, "$home/.cpan";
}

use strict;
if($[ > 5.005) {
	require warnings;
} else {
	$^W = 1;
}
use CPAN;
use CPAN::MyConfig;
use File::Basename;

my $dirname = dirname($0);
chomp($dirname = `pwd`) if $dirname eq ".";
push @INC, $dirname;

$CPAN::Config->{makepl_arg} = "LIB=$dirname INSTALLMAN1DIR=/tmp INSTALLMAN3DIR=/tmp" if $> != 0;
$CPAN::Config->{prerequisites_policy} = "follow";

foreach my $mod (qw(HTML::FormatText HTML::Parse Net::OSCAR)) {
	my $obj = CPAN::Shell->expand('Module', $mod);
	next if $obj->inst_version() and $mod ne "Net::OSCAR";
	print "Installing $mod...\n";
	$obj->install;
}

print "All modules installed!\n";
