#!/usr/bin/perl -w
use Slash::PSM;
use Data::Dumper;

$slashsite = Slash::PSM->new(1, "newsd", "mattdot");
require 'pdump';
#print Dumper($slashsite);
$slashsite->Section("articles");
$slashsite->Topic("news");
$slashsite->User("matthewg");
$slashsite->Story("somestory");
$slashsite->Comment("123");
$slashsite->FrontendVar("foo", "1", "Controls the bar");

