<?

$TEMPLATE["index"] = array(
	"title" => "Brandeis Wake-up Calls",
	"start" => "",
	"script" => "",
	"head" => "",
	"end" => "",
	"body" => <<<END
    <p>Finnegan is a wake-up call service. Think of it as a super-powered alarm clock.</p>
	<p>Once you register, you can use Finnegan to set up to 10 custom alarms. 
	  At each wake-up time, Finnegan will call your room phone and play a custom 
	  message of your choice. Press any key to tell Finnegan that you're 
	  awake. If you do not, Finnegan will snooze for 9 minutes and automatically 
	  call you back!</p>
	<p>To register for Finnegan, you will need to be next to your phone. 
	  For security, Finnegan will call you immediately with a unique 4 digit PIN 
	  code. You will need this code to set and modify your alarms.</p>
	<p>Finnegan has two modes:</p>
	<ul>
		<li><strong>Recurring Alarms</strong>

		<br />Recurring alarms are scheduled on a weekly basis.  For example, you can set an alarm for 9:00am on every Monday and Wednesday.  You can set recurring alarms to respect US national holidays or the Brandeis calendar.  That way, if the day is Tuesday but it is a Brandeis Monday, your Monday alarm will trigger.</li>
		<li><strong>One-Time Alarms</strong>
		<br />One-time alarms trigger on a particular date and time and can be scheduled up to one year in advance.</li>
	</ul>
	<p>Finnegan is a joint project of <a href="http://www.brancog.org/">the Computer Operators Group</a> and <a href="http://www.brandeis.edu/its/">Information Technology Services</a>.</p>
END
);

?>
