<?

$TEMPLATE["legal"] = array(
	"title" => "Finnegan: Legal Information",
	"start" => <<<END
<ul class="navigation">
<li><a href="wakes.php">View Alarms</a></li>
<li><a href="mkwake.php">Create New Alarm</a></li>
<li><a href="setpin.php">Change PIN or Log Out</a></li>
<li><a href="docs.php">Help With Finneagn</a></li>
</ul>
<h3>Legal Information</h3>
END
,

	"script" => "",
	"head" => "",
	"end" => ""
);

?>
