%p10_tokens = (
	PRIVMSG => "P",
	WHO => "H",
	WHOIS => "W",
	WHOWAS => "X",
	NICK => "N",
	SERVER => "S",
	TOPIC => "T",
	INVITE => "I",
	VERSION => "V",
	QUIT => "Q",
	SQUIT => "SQ",
	KILL => "D",
	INFO => "F",
	LINKS => "LI",
	STATS => "R",
	ERROR => "Y",
	AWAY => "A",
	CONNECT => "CO",
	PING => "G",
	PONG => "Z",
	PASS => "PA",
	WALLOPS => "WA",
	DESYNCH => "DS",
	TIME => "TI",
	SETTIME => "SE",
	RPING => "RI",
	RPONG => "RO",
	NAMES => "E",
	ADMIN => "AD",
	TRACE => "TR",
	NOTICE => "O",
	WALLCHOPS => "WC",
	CPRIVMSG => "CP",
	CNOTICE => "CN",
	JOIN => "J",
	PART => "L",
	LUSERS => "LU",
	MOTD => "MO",
	MODE => "M",
	KICK => "K",
	SILENCE => "U",
	GLINE => "GL",
	BURST => "B",
	CREATE => "C",
	DESTRUCT => "DE",
	END_OF_BURST => "EB",
	END_OF_BURST_ACK => "EA",
	JUPE => "JU",
	OPMODE => "OM",
	CLEARMODE => "CM",
);

%p10_tokens_rev = map { $p10_tokens{$_} => $_ } keys %p10_tokens;

1;
