#!/usr/bin/perl

# This is the script that vgetty launches when we dial a number

use strict;
use warnings;
use Modem::Vgetty;
our $v;

my($type, $extension, $timeout, $sample, $snooze_ok) = @ARGV;

sub vm_shutdown {
	if(@_ == 1) {
		$v->stop;
		$v->expect("READY");
	}
	$v->send("ATH0");
	$v->expect("READY");
	$v->shutdown;
	exit(shift);
}

$SIG{ALRM} = sub {vm_shutdown(4)};
alarm($timeout);

$v = new Modem::Vgetty;
$v->add_handler('BUSY_TONE', 'endh', sub { vm_shutdown(1); });
$v->add_handler('NO_DIAL_TONE', 'hangup', sub { vm_shutdown(2); });
$v->enable_events;

$v->dial($extension);
$v->waitfor("READY");

# User hangs up
$v->del_handler('BUSY_TONE', 'endh');
$v->add_handler('BUSY_TONE', 'endh', sub { vm_shutdown($snooze_ok ? 3 : 0); });

if($type eq "wake") {
	$v->add_handler('RECEIVED_DTMF', 'readnum', sub {
		$v->stop;
		$v->expect("READY");
		$v->play_and_wait("../rmd/wake/thanks.rmd");
		vm_shutdown(0, 1);
	});
}

$v->play_and_wait($sample);
$v->wait(1);
$v->expect("READY");
$v->play_and_wait($sample);
vm_shutdown($snooze_ok ? 3 : 0, 1);
