#!/usr/bin/perl

use Data::Dumper;
require "ABNF.pm";

#print Data::Dumper::Dumper($Parse::ABNF::ABNF), "\n";
$rule = "rule           =  rulename defined-as elements c-nl\n";
$ret = $Parse::ABNF::ABNF->matches("rule", $rule, qw(rulename defined-as elements));

print Data::Dumper::Dumper($ret), "\n";
