#!/usr/bin/perl

use strict;
use warnings;

foreach (@ARGV) {
	my $wav = $_;
	my $down = $wav;
	$down =~ s!wav/!raw-mono8/!;
	$down =~ s!.wav$!.raw!;
	print "Converting $wav to $down...\n";
	unlink($down);
	system("mkdir -p `dirname $down`");
	system("sox $wav -s -w -r 8000 -c 1 $down resample");
}
