

<H2>Yesterday's Statistics</H2>
<P>Yesterday we served up  pages.
Grand Total is 0 . 


<H2>Platforms</H2>
<TABLE><TR>
  <TD align=right>Linux </TD>
  <TD></TD>
</TR><TR>
  <TD align=right>Win </TD>
  <TD> </TD>
</TR><TR>
  <TD align=right>Mac </TD>
  <TD> </TD>
</TR><TR>
  <TD align=right>Other Unix </TD>
  <TD> </TD>
</TR><TR>
  <TD align=right>Other </TD>
  <TD> </TD>
</TR>
</TABLE>


<h2>Browsers</H2>
<TABLE>
<TR>
  <TD align=right>Netscape </TD>
  <TD> </TD>

</TR><TR>

  <TD align=right>IE </TD>
  <TD> </TD>
</TR><TR>
  <TD align=right>Lynx </TD>
  <TD> </TD>
</TR><TR>
  <TD align=right>Other </TD>
  <TD> </TD>
</TR>
</TABLE>

<TABLE></TABLE>