PROG = finnegan-call-h323
SOURCES := connection.cxx ep.cxx finnegan-call-h323.cxx nullchan.cxx wavchan.cxx

ifndef OPENH323DIR
OPENH323DIR=/usr/share/openh323
endif
ifndef PWLIBDIR
PWLIBDIR=/usr/share/pwlib
endif

include $(OPENH323DIR)/openh323u.mak

